### Import libraries

In [1]:
import pandas as pd
import numpy as np

### Load data

In [2]:
data_preprocessed = pd.read_csv("Absenteeism_preprocessed.csv")

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

         Date  Transportation Expense  Distance to Work  Age  \
0  2015-07-07                     289                36   33   
1  2015-07-14                     118                13   50   
2  2015-07-15                     179                51   38   
3  2015-07-16                     279                 5   39   
4  2015-07-23                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

### Create the targets

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [5]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets

In [7]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

         Date  Transportation Expense  Distance to Work  Age  \
0  2015-07-07                     289                36   33   
1  2015-07-14                     118                13   50   
2  2015-07-15                     179                51   38   
3  2015-07-16                     279                 5   39   
4  2015-07-23                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   

   Absenteeism Time in Hours  Excessive Absenteeism  
0                          4                      1  
1                          0                      0  
2                          2                      0  
3                          4                      1  
4                          2                      0

In [8]:
# we balance the dataset, good balance is around 45-44/ 40-60
targets.sum() / targets.shape[0] #around 46% are 1s

0.45571428571428574

In [9]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Date','Distance to Work',
                                           'Day of the Week','Daily Work Load Average'],axis=1)

In [10]:
data_with_targets is data_preprocessed

False

In [11]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

### Select inputs for the regression

In [12]:
data_with_targets.shape

(700, 12)

In [13]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

### Standardized the data

In [14]:
#from sklearn.preprocessing import StandardScaler
#absenteeism_scaler = StandardScaler()

In [15]:
# CUSTOM SCALER
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [16]:
unscaled_inputs.columns

Index(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'],
      dtype='object')

In [17]:
#choose the columns to scale (exclude the dummy variables)
#columns_to_scale = ['Month Value', 'Day of the Week', 'Transportation Expense', 'Distance to Work', 'Age',
       #'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children', 'Pets']
    
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [18]:
# declare a scaler object, specifying the columns you want to scale
absenteeism_scaler = CustomScaler(columns_to_scale)

In [19]:
#fit the data
absenteeism_scaler.fit(unscaled_inputs)

C:\Anaconda\lib\site-packages\sklearn\base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)


CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [20]:
#standardize the data using transform method
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [21]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.388293   
696         1         0         0         0    -0.388293   
697         1         0         0         0    -0.388293   
698         0         0         0         1    -0.388293   
699         0         0         0         1    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [22]:
scaled_inputs.shape

(700, 11)

### Split the data into training and testing and shuffle

#### Import relevant module

In [23]:
from sklearn.model_selection import train_test_split

#### Split data

In [24]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs,targets,train_size = 0.8, 
                                                    shuffle = True, random_state = 25)

In [25]:
print(x_train.shape,y_train.shape)

(560, 11) (560,)


In [26]:
print(x_test.shape,y_test.shape)

(140, 11) (140,)


### Logistic Regression with sklearn

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

#### Training the model

In [28]:
reg = LogisticRegression()

In [29]:
reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [30]:
reg.score(x_train,y_train)

0.775

#### Manually check the accuracy

In [31]:
model_outputs = reg.predict(x_train)
model_outputs

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,

In [32]:
np.sum(model_outputs == y_train) / model_outputs.shape[0]

0.775

#### Finding the intercept and coefficients

In [33]:
reg.intercept_

array([-1.78643525])

In [34]:
reg.coef_

array([[ 2.80722538,  0.35735658,  3.10842393,  0.84363757,  0.03184953,
         0.59812763, -0.28537127,  0.26173843, -0.03530415,  0.39901703,
        -0.39943888]])

In [35]:
feature_name = unscaled_inputs.columns.values

In [36]:
summary_table = pd.DataFrame(columns = ['Feature Name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature Name  Coefficient
0                 Reason_1     2.807225
1                 Reason_2     0.357357
2                 Reason_3     3.108424
3                 Reason_4     0.843638
4              Month Value     0.031850
5   Transportation Expense     0.598128
6                      Age    -0.285371
7          Body Mass Index     0.261738
8                Education    -0.035304
9                 Children     0.399017
10                    Pets    -0.399439

In [37]:
#add intercept to the summary table
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature Name  Coefficient
0                Intercept    -1.786435
1                 Reason_1     2.807225
2                 Reason_2     0.357357
3                 Reason_3     3.108424
4                 Reason_4     0.843638
5              Month Value     0.031850
6   Transportation Expense     0.598128
7                      Age    -0.285371
8          Body Mass Index     0.261738
9                Education    -0.035304
10                Children     0.399017
11                    Pets    -0.399439

#### Interpret the coefficients

In [38]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)
summary_table

Feature Name  Coefficient  Odds_ratio
0                Intercept    -1.786435    0.167556
1                 Reason_1     2.807225   16.563896
2                 Reason_2     0.357357    1.429546
3                 Reason_3     3.108424   22.385735
4                 Reason_4     0.843638    2.324808
5              Month Value     0.031850    1.032362
6   Transportation Expense     0.598128    1.818710
7                      Age    -0.285371    0.751735
8          Body Mass Index     0.261738    1.299187
9                Education    -0.035304    0.965312
10                Children     0.399017    1.490359
11                    Pets    -0.399439    0.670696

In [39]:
summary_table.sort_values('Odds_ratio',ascending=False)

Feature Name  Coefficient  Odds_ratio
3                 Reason_3     3.108424   22.385735
1                 Reason_1     2.807225   16.563896
4                 Reason_4     0.843638    2.324808
6   Transportation Expense     0.598128    1.818710
10                Children     0.399017    1.490359
2                 Reason_2     0.357357    1.429546
8          Body Mass Index     0.261738    1.299187
5              Month Value     0.031850    1.032362
9                Education    -0.035304    0.965312
7                      Age    -0.285371    0.751735
11                    Pets    -0.399439    0.670696
0                Intercept    -1.786435    0.167556

A feature is not particularly important if:
- Coefficient is around 0
- Odds ratio is around 1

Reason_3: the odds of someone absent because of reason 3 are 20 times higher than no reason (reason_0 which is the base model).

Transportation Expense: since we standardized this variable, there is no interpretation from the odds ratio.

#### Testing our model

In [40]:
reg.score(x_test,y_test)

0.7

In [43]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.84578583, 0.15421417],
       [0.38914043, 0.61085957],
       [0.19959439, 0.80040561],
       [0.87635443, 0.12364557],
       [0.78957994, 0.21042006],
       [0.66201702, 0.33798298],
       [0.51280408, 0.48719592],
       [0.77153647, 0.22846353],
       [0.77407431, 0.22592569],
       [0.51280408, 0.48719592],
       [0.77153647, 0.22846353],
       [0.94337355, 0.05662645],
       [0.8194531 , 0.1805469 ],
       [0.32273754, 0.67726246],
       [0.78654243, 0.21345757],
       [0.88234384, 0.11765616],
       [0.4459372 , 0.5540628 ],
       [0.76831492, 0.23168508],
       [0.22209594, 0.77790406],
       [0.30205862, 0.69794138],
       [0.36775492, 0.63224508],
       [0.65997939, 0.34002061],
       [0.38482608, 0.61517392],
       [0.71880581, 0.28119419],
       [0.25444218, 0.74555782],
       [0.17174937, 0.82825063],
       [0.94481334, 0.05518666],
       [0.31958627, 0.68041373],
       [0.54214439, 0.45785561],
       [0.25116042, 0.74883958],
       [0.

In [44]:
predicted_proba.shape

(140, 2)

#### Save our model

In [45]:
import pickle

In [46]:
#save the model
with open('model','wb') as file: #file name, write byte
    pickle.dump(reg,file) #reg: object to be dumped

In [47]:
#save the custom scaler:
with open('scaler','wb') as file: #file name, write byte
    pickle.dump(absenteeism_scaler,file) #reg: object to be dumped